name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    #git@github.com:davidscmx/simple-waymo-open-dataset-reader.git
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Checkout the Simple Waymo Open Dataset Reader
        uses: actions/checkout@v3
        with:
          repository: davidscmx/simple-waymo-open-dataset-reader
          path: 3rd_party
      - name: Install the Simple Waymo Open Dataset Reader
          run: |
          cd 3rd_party
          python setup.py install
          cd ..
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude 3rd_party
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude 3rd_party
      - name: Test with pytest
        run: |
          pytest
